export const actionTypes = {
    FETCH_ASYNC_SINGLE_PRODUCT: "FETCH_ASYNC_SINGLE_PRODUCT",
    FETCH_ASYNC_PRODUCTS: "FETCH_ASYNC_PRODUCTS",
    ADD_PRODUCTS: "ADD_PRODUCTS",
    GET_PRODUCT: "GET_PRODUCT",
    REMOVE_PRODUCT: "REMOVE_PRODUCT"
}